name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Dev_Deploy:
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/aks-deploy.yml@main
    with:
      appType: 'angular'
      appName: 'frontend'
      appEnv: 'dev'
    secrets:
      vault_token: ${{ secrets.vault_token }}
